### ISSUE TITLE
ability to use something other than swig, like nunjucks?  or is this module outdated?

### ISSUE THREAD

**Issue by niftylettuce** [koajs/onerror#10]
looking to use this in koa@next - or a better alternative?

**Comment by Spy-Seth** [comment]
Did you find an alternative? I'm looking to use this kind of middleware too.

**Comment by coderhaoxin** [comment]
There are 2 PRs in https://github.com/koajs/error for more render engines

**Comment by Spy-Seth** [comment]
I was more asking for the `koa@next` compatibility.

**Comment by niftylettuce** [comment]
i basically wrote my own error handler, would you like to see it?  email me niftylettuce@gmail.com, i'll prob open source it too

**Comment by jonathanong** [comment]
it would be nice to have a canonical error handler. if anyone wants to help maintain https://github.com/koajs/error, let me know!

**Comment by dead-horse** [comment]
it is easy to render your own template engine like this:

```js
  onerror(app, {
    html: function(err) {
      const status = err.status;
      const code = err.code;
      const message = err.message;
      this.render('err.html', {message, status, code});  // implement with any template engine you like
    }
  });
```

**Comment by Spy-Seth** [comment]
So maybe I miss understood this middleware (`koajs/onerror`): is it a super `koajs/error` that also manage the `app.on('error', ...)`? By reading again the readme it appear not... So my initial need go await. But the question on the `koajs/error` render engine  is still a good one.

> it would be nice to have a canonical error handler. 

Exactly, it's one of the thing I wrote myself with koajs.
