### ISSUE TITLE
How to set up json for response error messages.

### ISSUE THREAD

**Issue by drake-jin** [koajs/onerror#25]
# code

``` js

const onerror = require('koa-onerror')
const app = new Koa()

onerror(app, {
  accepts: 'json',
})

.... occurred an error.

```
### Your code print out this message 

> (node:25492) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: options.accepts.call is not a function
> (node:25492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

- How to set up JSON for response error messages when my node program has an error?
- I think your document add some code and comment for this situation. If you reply to my issue, I will send P.R. 
 - I saw this link( https://github.com/koajs/onerror/blob/master/index.js#L38), so what should I do? What do you want to me? please, more tell me some guide

**Comment by dead-horse** [comment]
accepts must be a function like: 

```
accepts() {
  if (this.path.endsWith('.json')) return 'json';
  return 'html';
}
```

**Comment by marswong** [comment]
simply set `options.accepts` like:

```js
onerror(app, {
  accepts() {
    if (this.get('accept').includes('json')) return 'json';
    return 'html';
  },
});
```

and remember to set the `Accept` header to be `application/json` for each request, take `fetch` as an example:

```js
fetch('/xxx', {
  headers: {
    'Accept': 'application/json',
  },
  method: 'xxx',
  ...
})
.then(res => res.json)
.then((res) => {
  // default response format:
  // {
  //   error: 'xxx'
  // }
})
```
