### ISSUE TITLE
404 page not work

### ISSUE THREAD

**Issue by helloyou2012** [koajs/onerror#9]
Test:

```
it('should 404 error ok', function (done) {
  var app = koa();
  app.on('error', function () {});
  onerror(app);

  request(app.callback())
  .get('/404')
  .set('Accept', 'text/html')
  .expect(/<p>Looks like something broke!<\/p>/, done);
});
```

the reason is: [https://github.com/koajs/koa/blob/master/lib/application.js#L130](https://github.com/koajs/koa/blob/master/lib/application.js#L130)

**Comment by coderhaoxin** [comment]
> Because of koa-router 404 not throw err but just set status=404

So, what's the problem with this module?

**Comment by dead-horse** [comment]
404 is not error

**Comment by helloyou2012** [comment]
But `this.throw(404)` will go to error page.

**Comment by dead-horse** [comment]
`this.throw(404)` will throw a error with status 404, so it will hit the error page, you should handle 4xx error by yourself in `onerror`  or use `try catch`.

**Comment by helloyou2012** [comment]
Alright, maybe I need to use error middleware instead of this. But still thanks.
